events {
}

http {
    # Define a group of backend servers.
    # Nginx distributes incoming requests among these servers
    # using round-robin load balancing by default.
    upstream backend {
        server server1:7000;
        server server2:7000;
        server server3:7000;
    }

    server {
        # Nginx listens for HTTP requests on port 80.
        listen 80;

        # Handle incoming requests.
        location / {
            # Forward the request to one of the servers
            # in the backend upstream group.
            proxy_pass http://backend;
        }
    }
}