events{

}

http{
    server{
        listen 80; # serve running port in container of nginx
        location /{
            proxy_pass http://server:6000; # container url of server
        }
    }
}

